sudo: false
language: d
d:
  - dmd

os:
  - linux
  - osx

env:
  - BUILD=dub

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+([+-]\S*)*$/

script:
  - make all
#  - dub build --config "minisat"
#  - dub build --config "picosat"

test:
  - make test
